[package]
name = "chris-scp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.6.3"
clap = { version = "4.5.2", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
snafu = "0.8.2"
thiserror = "1.0.58"
reqwest = { version = "0.11.26", features = ["rustls"], default-features = false }
reqwest-middleware = "0.2.4"
reqwest-retry = "0.4.0"
camino = "1.1.6"
fs-err = { version = "2.11.0", features = ["tokio"] }
tokio-util = { version = "0.7.10", features = ["io-util"] }
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros", "full"] }
serde = { version = "1.0.197", features = ["derive"] }
seahash = { version = "4.1.0", features = ["use_std"] }
