[package]
name = "oxidicom"
description = "DICOM receiver for ChRIS backend"
version = "2.0.0-a1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.7.0"
snafu = "0.8.2"
thiserror = "1.0.61"
camino = "1.1.7"
fs-err = "2.11.0"
serde = { version = "1.0.202", features = ["derive"] }
seahash = { version = "4.1.0", features = ["use_std"] }
envmnt = "0.10.4"
regex = "1.10.4"
opentelemetry = { version = "0.23.0", features = ["metrics"] }
opentelemetry-stdout = { version = "0.4.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.16.0", features = ["trace", "grpc-tonic"] }
opentelemetry-semantic-conventions = "0.15.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
aliri_braid = "0.4.0"
anyhow = "1.0.86"
sqlx = { version = "0.7.4", features = ["postgres", "time", "runtime-tokio-rustls", "macros"], default-features = false }
tokio = { version = "1.37.0", features = ["full"] }
futures = "0.3.30"
time = { version = "0.3.36", features = ["macros", "parsing"] }
ulid = "1.1.2"

[dev-dependencies]
rstest = "0.19.0"
walkdir = "2.5.0"
chris = { version = "0.5.0-a.1", features = ["rustls"], default-features = false }
tokio = { version = "1.36.0", features = ["rt"] }
