[package]
name = "chris-scp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.6.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
snafu = "0.8.2"
thiserror = "1.0.58"
reqwest = { version = "0.11.26", features = ["rustls-tls", "blocking", "json"], default-features = false }
camino = "1.1.6"
fs-err = "2.11.0"
serde = { version = "1.0.197", features = ["derive"] }
seahash = { version = "4.1.0", features = ["use_std"] }
envmnt = "0.10.4"

[dev-dependencies]
rstest = "0.18.2"
