[package]
name = "oxidicom"
description = "DICOM receiver for ChRIS backend"
version = "3.0.0-a1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.7.0"
snafu = "0.8.2"
thiserror = "1.0.61"
camino = { version = "1.1.7", features = ["serde1"] }
fs-err = { version = "2.11.0", features = ["tokio"] }
serde = { version = "1.0.203", features = ["derive"] }
seahash = { version = "4.1.0", features = ["use_std"] }
regex = "1.10.4"
opentelemetry = { version = "0.23.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.16.0", features = ["trace", "grpc-tonic"] }
opentelemetry-semantic-conventions = "0.15.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
aliri_braid = "0.4.0"
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.30"
time = { version = "0.3.36", features = ["macros", "parsing"] }
ulid = "1.1.2"
figment = { version = "0.10.19", features = ["env"] }
celery = "0.5.5"
humantime-serde = "1.1.1"

[dev-dependencies]
rstest = "0.21.0"
walkdir = "2.5.0"
chris = { version = "0.5.0-a.1", features = ["rustls"], default-features = false }
tokio = { version = "1.36.0", features = ["rt"] }
reqwest = { version = "0.12.4", features = ["json"] }
