[package]
name = "oxidicom"
description = "DICOM receiver for ChRIS backend"
version = "1.0.0-b.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.6.3"
snafu = "0.8.2"
thiserror = "1.0.58"
reqwest = { version = "0.12.0", features = ["rustls-tls", "blocking", "json"], default-features = false }
camino = "1.1.6"
fs-err = "2.11.0"
serde = { version = "1.0.197", features = ["derive"] }
seahash = { version = "4.1.0", features = ["use_std"] }
envmnt = "0.10.4"
regex = "1.10.3"
opentelemetry = { version = "0.22.0", features = ["metrics"] }
opentelemetry-stdout = { version = "0.3.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.22.1" }
opentelemetry-otlp = { version = "0.15.0", features = ["reqwest-blocking-client", "http-proto"], default-features = false }
opentelemetry-semantic-conventions = "0.14.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.7.0", features = ["v4"] }
aliri_braid = "0.4.0"
anyhow = "1.0.81"

[dev-dependencies]
rstest = "0.18.2"
walkdir = "2.5.0"
chris = { version = "0.5.0-a.1", features = ["rustls"], default-features = false }
tokio = { version = "1.36.0", features = ["rt"] }
