services:
  rabbitmq:
    image: docker.io/library/rabbitmq:3
    ports:
      - "5672:5672"
  orthanc:
    image: docker.io/jodogne/orthanc-plugins:1.12.3
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - orthanc:/var/lib/orthanc/db
    network_mode: "host"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:8042/patients"]
      interval: 2s
      timeout: 4s
      retries: 3
      start_period: 30s
  get-data:
    image: ghcr.io/fnndsc/utils:7c65939
    command: /get_data.sh
    volumes:
      - ./get_data.sh:/get_data.sh:ro
    depends_on:
      orthanc:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    profiles:
      - tools
    network_mode: "host"  # so that Orthanc in a container can send data out

volumes:
  orthanc:
