services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.6-rc1
    environment:
      ZO_ROOT_USER_EMAIL: dev@babymri.org
      ZO_ROOT_USER_PASSWORD: chris1234
      ZO_DATA_DIR: /data
    ports:
      - "5080:5080"
    volumes:
      - openobserve:/data
    restart: unless-stopped

  otel-collector:
    image: docker.io/otel/opentelemetry-collector:0.101.0
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro

volumes:
  openobserve:
