{
 "title": "ChRIS PACS Retrieval Performance",
 "description": "Monitoring of the oxidicom component of ChRIS backend.",
 "tags": [ "ChRIS" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "spanName",
    "label": "Span Name",
    "query": "association,\npush_to_chris,\ngetset_number_of_series_related_instances,\nregister_all_attempted_pushes,"
   }
  ]
 },
 "panels": [
  {
   "title": "CUBE Response Timing Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "a3ab68a4", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "\"oxidicom\""
       ]
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "\"push_to_chris\""
       ]
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Oxidicom / Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"kk\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"kk\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Oxidicom / CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"kk\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"kk\"})",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "ChRIS Backend WSGI API Server / CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"chris-server\", namespace=\"kk\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"chris-server\", namespace=\"kk\"})",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "ChRIS Backend WSGI API Server / Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"kk\", container!=\"\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"chris-server\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n* on (pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"chris-server\", namespace=\"kk\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Oxidicom / Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n    irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n    * on (namespace, pod) group_left()\n    kube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"$namespace\"}\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oxidicom / Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n    irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n    * on (namespace, pod) group_left()\n    kube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"$namespace\"}\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oxidicom / Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n    rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[$__rate_interval])\n    * on (namespace, pod) group_left()\nkube_pod_labels{label_app_kubernetes_io_name=\"oxidicom\", namespace=\"$namespace\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "7596b8a2", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "\"oxidicom\""
       ]
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "\"$spanName\""
       ]
      }
     ],
     "limit": 300,
     "tableType": "traces"
    }
   ]
  }
 ]
}