# docker run -v $PWD/data:/data -e ZO_DATA_DIR="/data" -p 5080:5080 \
#    -e ZO_ROOT_USER_EMAIL="root@example.com" -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
#    public.ecr.aws/zinclabs/openobserve:latest

version: "3.9"

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.9.1
    environment:
      ZO_ROOT_USER_EMAIL: dev@babymri.org
      ZO_ROOT_USER_PASSWORD: chris1234
      ZO_DATA_DIR: /data
    ports:
      - "5080:5080"
    volumes:
      - openobserve:/data
    restart: unless-stopped
  otel-collector:
    image: docker.io/otel/opentelemetry-collector:0.96.0
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"
volumes:
  openobserve:
