name: CI

on:
  push:
    branches: [ master ]
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
    paths:
      - '.github/**'
      - '**.rs'
      - 'Cargo.*'
      - 'Dockerfile'
      - 'docker-compose.yml'
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Start services
      run: docker compose up -d
    - name: Download example data
      run: docker compose run --rm get-data
    - name: Compile test binary
      run: cargo test --no-run
    - name: Run tests
      run: cargo test
